# Master docker-compose file for all services
# Run from /srv/docker directory

version: '3.8'

# This file creates the shared proxy network
# Individual services are in their own directories

networks:
  proxy:
    name: proxy
    driver: bridge
