api:
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /config
    watch: true

# For local development, comment out certificatesResolvers
# For production with real domain:
certificatesResolvers:
  cloudflare:
    acme:
      email: gutmutcode@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

# Uncomment for local development (self-signed certs)
# tls:
#   options:
#     default:
#       minVersion: VersionTLS12
